version: '3.4'

volumes:
  gem_cache:
  postgres:

services:
  bilinho:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "bundle install && bundle exec rails s -b 0.0.0.0"
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems

  postgres:
    image: postgres:12.1
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
